import {createClient} from '@supabase/supabase-js'

export const supabase = createClient('https://gnkloatdlrumbeqrpzot.supabase.co' , 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdua2xvYXRkbHJ1bWJlcXJwem90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTE1NzQ4MjIsImV4cCI6MjAwNzE1MDgyMn0.QYDJoKju259N5u34YMkGRoVX5mNVgeUBrFCajPek8T8')